//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.LocalizationSystem
{
    
    
    public class LocalizationKeys
    {
        
        public const string LABEL_LANGUAGE = "LABEL_LANGUAGE";
        
        public const string LABEL_HELLO = "LABEL_HELLO";
        
        public const string BUTTON_HELLO = "BUTTON_HELLO";
        
        public const string start_game = "start_game";
        
        public const string settings = "settings";
        
        public const string sound = "sound";
        
        public const string music = "music";
    }
}
