//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.LocalizationSystem
{
    
    
    public class LocalizationKeys
    {
        
        public const string LABEL_LANGUAGE = "LABEL_LANGUAGE";
        
        public const string LABEL_HELLO = "LABEL_HELLO";
        
        public const string BUTTON_HELLO = "BUTTON_HELLO";
        
        public const string start_game = "start_game";
        
        public const string settings = "settings";
        
        public const string sound = "sound";
        
        public const string music = "music";
        
        public const string title_paused = "title_paused";
        
        public const string @continue = "continue";
        
        public const string title_level = "title_level";
        
        public const string status_perfect = "status_perfect";
        
        public const string status_good = "status_good";
        
        public const string status_amazing = "status_amazing";
        
        public const string result_win = "result_win";
        
        public const string result_lose = "result_lose";
        
        public const string levels_no_more = "levels_no_more";
        
        public const string game_quit = "game_quit";
        
        public const string game_quit_title = "game_quit_title";
        
        public const string privacy = "privacy";
        
        public const string terms_condition = "terms_condition";
        
        public const string submit = "submit";
        
        public const string confirm = "confirm";
        
        public const string cancel = "cancel";
        
        public const string exit = "exit";
        
        public const string spin_wheel = "spin_wheel";
        
        public const string spin_wheel_instructions = "spin_wheel_instructions";
        
        public const string spin = "spin";
        
        public const string day = "day";
        
        public const string reward_amount = "reward_amount";
        
        public const string daily_reward = "daily_reward";
        
        public const string rewards = "rewards";
        
        public const string tap_to_continue = "tap_to_continue";
        
        public const string vibrate = "vibrate";
        
        public const string language = "language";
    }
}
